name: Unit Tests

on:
  workflow_dispatch:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'zulu'
      #      - name: Initialize CodeQL
      #        uses: github/codeql-action/init@v2
      #        with:
      #          languages: java
#      - name: Build with Infer
#        uses: docker://ghcr.io/martinwitt/infer-train:master
#        with:
#          build-command: "./gradlew build"
#          use-annotations: "true"
      - name: Build with Gradle
        uses: gradle/gradle-build-action@937999e9cc2425eddc7fd62d1053baf041147db7
        with:
          arguments: test
      #      - name: Perform CodeQL Analysis
      #        uses: github/codeql-action/analyze@v2
      - name: Upload to Coverity
        uses: checkity/upload@v1
        with:
          # Comma separated list of coverage files to upload, supports globs.
          file-pattern: '**/jacocoTestReport.xml'

          # The GitHub token used to validate repository access when uploading coverage reports.
          repo-token: ${{ secrets.GITHUB_TOKEN }}
      - name: Run JMH
        uses: gradle/gradle-build-action@937999e9cc2425eddc7fd62d1053baf041147db7
        if: startsWith(github.event.head_commit.message, '[JMH]')
        with:
          arguments: benchmark:jmh