name: Unit Tests

on:
  workflow_dispatch:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'zulu'
      #      - name: Initialize CodeQL
      #        uses: github/codeql-action/init@v2
      #        with:
      #          languages: java
#      - name: Build with Infer
#        uses: docker://ghcr.io/martinwitt/infer-train:master
#        with:
#          build-command: "./gradlew build"
#          use-annotations: "true"
      - name: Build with Gradle
        run: "./gradlew build"
      - name: Tree new bee
        run: "pwd"
      - name: Add coverage to PR (dash-core-impl)
        uses: madrapps/jacoco-report@v1.3
        with:
          paths: ${{ github.workspace }}/dash-core-impl/build/reports/jacoco/test/jacocoTestReport.xml
          token: ${{ secrets.GITHUB_TOKEN }}
          min-coverage-overall: 70
          min-coverage-changed-files: 60
      - name: Add coverage to PR (dash-core-api)
        uses: madrapps/jacoco-report@v1.3
        with:
          paths: ${{ github.workspace }}/dash-core-api/build/reports/jacoco/test/jacocoTestReport.xml
          token: ${{ secrets.GITHUB_TOKEN }}
          min-coverage-overall: 70
          min-coverage-changed-files: 60
      #      - name: Perform CodeQL Analysis
      #        uses: github/codeql-action/analyze@v2
      - name: Run JMH
        uses: gradle/gradle-build-action@937999e9cc2425eddc7fd62d1053baf041147db7
        if: startsWith(github.event.head_commit.message, '[JMH]')
        with:
          arguments: benchmark:jmh